$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Speech

$projectRoot = Split-Path -Parent $PSScriptRoot
$outputDirectory = Join-Path (Join-Path $projectRoot "src") "generated"
$outputPath = Join-Path $outputDirectory "audio_test_sample.h"
$wavePath = Join-Path ([System.IO.Path]::GetTempPath()) ("mxchip-speech-" + [guid]::NewGuid().ToString("N") + ".wav")
$sampleRate = 16000
$voice = "Microsoft David Desktop"
$phrase = "Audio test."

try {
  $synth = [System.Speech.Synthesis.SpeechSynthesizer]::new()
  try {
    $synth.SelectVoice($voice)
    $synth.Rate = 2
    $format = [System.Speech.AudioFormat.SpeechAudioFormatInfo]::new(
      $sampleRate,
      [System.Speech.AudioFormat.AudioBitsPerSample]::Sixteen,
      [System.Speech.AudioFormat.AudioChannel]::Mono
    )
    $synth.SetOutputToWaveFile($wavePath, $format)
    $synth.Speak($phrase)
  } finally {
    $synth.Dispose()
  }

  $wave = [System.IO.File]::ReadAllBytes($wavePath)
  if ($wave.Length -lt 12 -or [System.Text.Encoding]::ASCII.GetString($wave, 0, 4) -ne "RIFF" -or [System.Text.Encoding]::ASCII.GetString($wave, 8, 4) -ne "WAVE") {
    throw "Speech synthesis did not produce a WAV file."
  }

  $validFormat = $false
  $dataOffset = -1
  $dataLength = 0
  $offset = 12
  while ($offset + 8 -le $wave.Length) {
    $chunk = [System.Text.Encoding]::ASCII.GetString($wave, $offset, 4)
    $length = [BitConverter]::ToUInt32($wave, $offset + 4)
    $start = $offset + 8
    if ($length -gt $wave.Length - $start) {
      throw "The synthesized WAV file contains a truncated chunk."
    }
    if ($chunk -eq "fmt ") {
      if ($length -lt 16 -or [BitConverter]::ToUInt16($wave, $start) -ne 1 -or [BitConverter]::ToUInt16($wave, $start + 2) -ne 1 -or [BitConverter]::ToUInt32($wave, $start + 4) -ne $sampleRate -or [BitConverter]::ToUInt16($wave, $start + 14) -ne 16) {
        throw "The synthesized speech must be 16 kHz, 16-bit mono PCM."
      }
      $validFormat = $true
    }
    if ($chunk -eq "data") {
      $dataOffset = $start
      $dataLength = $length
    }
    $offset = $start + $length + ($length % 2)
  }
  if (-not $validFormat -or $dataOffset -lt 0 -or $dataLength -eq 0 -or $dataLength % 2 -ne 0) {
    throw "The synthesized WAV file has no valid PCM sample data."
  }

  $sampleCount = [int]($dataLength / 2)
  if ($sampleCount -gt 24000) {
    throw "The synthesized speech exceeds 1.5 seconds; increase the synthesis rate before regenerating."
  }
  $samples = [int16[]]::new($sampleCount)
  $peak = 0
  for ($i = 0; $i -lt $sampleCount; $i++) {
    $samples[$i] = [BitConverter]::ToInt16($wave, $dataOffset + $i * 2)
    $peak = [Math]::Max($peak, [Math]::Abs([int]$samples[$i]))
  }
  if ($peak -eq 0) {
    throw "The synthesized speech contains only silence."
  }

  $header = [System.Text.StringBuilder]::new()
  [void]$header.AppendLine("// Generated by tools/generate-audio-samples.ps1 using $voice; phrase: $phrase")
  [void]$header.AppendLine("#pragma once")
  [void]$header.AppendLine("#include <stddef.h>")
  [void]$header.AppendLine("#include <stdint.h>")
  [void]$header.AppendLine("")
  [void]$header.AppendLine("namespace {")
  [void]$header.AppendLine("  const int16_t kAudioWaveforms[3][256] = {")
  for ($waveform = 0; $waveform -lt 3; $waveform++) {
    [void]$header.AppendLine("    {")
    for ($i = 0; $i -lt 256; $i += 16) {
      $values = @()
      for ($j = $i; $j -lt $i + 16; $j++) {
        $phase = 2.0 * [Math]::PI * $j / 256.0
        $value = [Math]::Sin($phase)
        if ($waveform -eq 1) {
          $value = 4.0 * [Math]::Abs($j / 256.0 - 0.5) - 1.0
        } elseif ($waveform -eq 2) {
          $value = ($value + [Math]::Sin(3.0 * $phase) / 3.0 + [Math]::Sin(5.0 * $phase) / 5.0) / (1.0 + 1.0 / 3.0 + 1.0 / 5.0)
        }
        $sample = [int][Math]::Round(3000.0 * $value)
        $values += $sample.ToString([System.Globalization.CultureInfo]::InvariantCulture)
      }
      [void]$header.AppendLine("      " + ($values -join ", ") + ",")
    }
    [void]$header.AppendLine("    },")
  }
  [void]$header.AppendLine("  };")
  [void]$header.AppendLine("  constexpr unsigned int kSpeechSampleRate = $sampleRate;")
  [void]$header.AppendLine("  const int16_t kSpeechSamples[] = {")
  for ($i = 0; $i -lt $sampleCount; $i += 16) {
    $values = @()
    for ($j = $i; $j -lt [Math]::Min($i + 16, $sampleCount); $j++) {
      $sample = [int][Math]::Round($samples[$j] * 3000.0 / $peak)
      $values += $sample.ToString([System.Globalization.CultureInfo]::InvariantCulture)
    }
    [void]$header.AppendLine("    " + ($values -join ", ") + ",")
  }
  [void]$header.AppendLine("  };")
  [void]$header.AppendLine("  constexpr size_t kSpeechSampleCount = sizeof(kSpeechSamples) / sizeof(kSpeechSamples[0]);")
  [void]$header.AppendLine("}")
  New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
  [System.IO.File]::WriteAllText($outputPath, $header.ToString(), [System.Text.Encoding]::ASCII)
  Write-Output "Generated ${outputPath}: $sampleCount samples at $sampleRate Hz; peak normalized to 3000/32767."
} finally {
  if (Test-Path -LiteralPath $wavePath) {
    Remove-Item -LiteralPath $wavePath
  }
}
